test: &default

  # Credentials for REST APIs
  client_id: EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  client_secret: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: nosotros_api1.monigoty.com
  password: 1377961924
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AyNduxEtpH-4jdqkTo0eKGLbZsuO
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: web@monigoty.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
